export enum WebSocketDataTypeEnum {
    ORDER_EDIT = "ORDER_EDIT",
    EMPLOYEE_EDIT = "EMPLOYEE_EDIT",
    PASSENGER_EDIT = "PASSENGER_EDIT",
    ORDER_LIST_UPDATE = "ORDER_LIST_UPDATE",
    ORDERS_DISTRIBUTION_UPDATE = "ORDERS_DISTRIBUTION_UPDATE",
    PASSENGER_LIST_UPDATE = "PASSENGER_LIST_UPDATE"
}
